platform :ios, '8.0'

target 'ShangHaiProvidentFund' do

pod 'SDWebImage', '~>3.7'

pod 'MJExtension' 

pod 'AFNetworking', '~> 3.0'

pod 'YYCache'

pod 'BaiduMapKit' #百度地图SDK

# 'node_modules'目录一般位于根目录中
# 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
pod 'React', :path => '../node_modules/react-native', :subspecs => [
'Core',
'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
'RCTText',
'RCTNetwork',
'RCTWebSocket', # 这个模块是用于调试功能的
'RCTImage',
'BatchedBridge', #RN版本高于0.45之后必须导入
# 在这里继续添加你所需要的模块
]
# 如果你的RN版本 >= 0.42.0，则加入下面这行
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

end
